### ISSUE TITLE
Update podspec

### ISSUE THREAD

**Issue by ahmedraad** [mrustaa/ContainerController#10]
Can please update podspec version so we can be able to install new changes

**Comment by penguinbee** [comment]
https://github.com/penguinbee/ContainerController/commit/f6b016390ce91002c3f7c3370950e640c498bb56

**Comment by mrustaa** [comment]
Sorry, I just haven't updated "podspec" for a long time.
I have already forgotten how to do it.

**Comment by mrustaa** [comment]
It seems to have succeeded to update "podspec"
  up to version 1.1.4
