### ISSUE TITLE
ContainerController issues during rotation

### ISSUE THREAD

**Issue by adamdahan** [mrustaa/ContainerController#9]
Hey

I am having an issue where the my Apps orientation settings are all off and the app is only supposed to work in Portrait but one of my view controllers uses your ContainerController. The problem is, when you rotate the device upside down just for fun -> Your ContainerController goes bezerk and jumps all over the place. 

Are you aware of this issue?

**Comment by adamdahan** [comment]
The culprit of the issue is "rotated" in ContainerController. It does not respect if the phone has orientation disabled.

**Comment by duchuy-13** [comment]
@adamdahan hey I have same issue, and I found the work around for this is:
```
container = ContainerController(addTo: self, layout: layout)
NotificationCenter.default.removeObserver(container, name: UIDevice.orientationDidChangeNotification, object: nil)
```

**Comment by mrustaa** [comment]
I noticed this problem.
  I will try to solve it as soon as possible.

**Comment by ahmedraad** [comment]
hello @mrustaa 

Is there any fix coming soon?

**Comment by mrustaa** [comment]
**I fixed it**. @adamdahan Sorry for the long delay

**Comment by ahmedraad** [comment]
@mrustaa Great, Thanks
